// reference: interface generated by chatGPT based on demo data
interface IApiDrinkIdData {
    drinks: {
      strDrink: string;
      strDrinkThumb: string;
      idDrink: string;
    }[];
  }
  interface IApiFoodRecipeData {
    recipes: IFoodRecipe[];
  }
  
  interface IFoodRecipe {
    vegetarian: boolean;
    vegan: boolean;
    glutenFree: boolean;
    dairyFree: boolean;
    veryHealthy: boolean;
    cheap: boolean;
    veryPopular: boolean;
    sustainable: boolean;
    lowFodmap: boolean;
    weightWatcherSmartPoints: number;
    gaps: string;
    preparationMinutes?: number | null;
    cookingMinutes?: number | null;
    aggregateLikes: number;
    healthScore: number;
    creditsText: string;
    license: string;
    sourceName: string;
    pricePerServing: number;
    extendedIngredients: IFoodIngredient[];
    id: number;
    title: string;
    readyInMinutes: number;
    servings: number;
    sourceUrl: string;
    image: string;
    imageType: string;
    nutrition: INutrition;
    summary: string;
    cuisines: string[];
    dishTypes: string[];
    diets: string[];
    occasions: string[];
    instructions: string;
    analyzedInstructions: {
      name: string;
      steps: IFoodStep[];
    }[];
    originalId?: number | null;
    spoonacularScore: number;
    spoonacularSourceUrl: string;
  }
  interface INutrition {
    nutrients: Nutrient[];
    properties: Property[];
    flavonoids: Flavonoid[];
    ingredients: Ingredient[];
    caloricBreakdown: CaloricBreakdown;
    weightPerServing: WeightPerServing;
  }
  
  interface Nutrient {
    name: string;
    amount: number;
    unit: string;
    percentOfDailyNeeds: number;
  }
  
  interface Property {
    name: string;
    amount: number;
    unit: string;
  }
  
  interface Flavonoid {
    name: string;
    amount: number;
    unit: string;
  }
  
  interface IngredientNutrient {
    name: string;
    amount: number;
    unit: string;
    percentOfDailyNeeds: number;
  }
  
  interface Ingredient {
    id: number;
    name: string;
    amount: number;
    unit: string;
    nutrients: IngredientNutrient[];
  }
  
  interface CaloricBreakdown {
    percentProtein: number;
    percentFat: number;
    percentCarbs: number;
  }
  
  interface WeightPerServing {
    amount: number;
    unit: string;
  }
  interface IFoodStep {
    number: number;
    step: string;
    ingredients: {
      id: number;
      name: string;
      localizedName: string;
      image: string;
    }[];
    equipment: {
      id: number;
      name: string;
      localizedName: string;
      image: string;
    }[];
    length?: {
      number: number;
      unit: string;
    };
  }
  interface IFoodIngredient {
    id: number;
    aisle: string;
    image: string;
    consistency: string;
    name: string;
    nameClean: string;
    original: string;
    originalName: string;
    amount: number;
    unit: string;
    meta: string[];
    measures: {
      us: {
        amount: number;
        unitShort: string;
        unitLong: string;
      };
      metric: {
        amount: number;
        unitShort: string;
        unitLong: string;
      };
    };
  }
  interface IUserInfo {
    id: string;
    googleId: string;
    username: string;
    email: string;
    allergies: string[];
    favFoods: number[];
    favDrinks: number[];
    weeklyCalories: number[];
    ingredients: string[];
    icon: Buffer;
  }
  interface IAppContextType {
    username: string | undefined;
    email: string | undefined;
    id: string | undefined;
    allergies: string[];
    favFoods: number[];
    favDrinks: number[];
    weeklyCalories: number[];
    ingredients: string[];
    icon: Buffer | undefined;
    onChangeUsername: (username: string | undefined) => void;
    onChangeEmail: (email: string | undefined) => void;
    onChangeId: (id: string | undefined) => void;
    onChangeAllergies: (allergies: string[]) => void;
    onChangeFavFoods: (favFoods: number[]) => void;
    onChangeFavDrinks: (favDrinks: number[]) => void;
    onChangeWeeklyCalories: (weeklyCalories: number[]) => void;
    onChangeIngredients: (ingredients: string[]) => void;
    onChangeBuffer: (icon: Buffer | undefined) => void;
  }
  
  interface ICodeContextType {
    code: string;
    freeze: number[];
    attempt: number;
    disabled: boolean;
    time: number;
    onChangeCode: (code:string)=>void;
    onChangeFreeze: (freeze:number[])=>void;
    onChangeAttempt: (attempt:number)=>void;
    onChangeDisabled : (disabled: boolean)=>void;
    onChangeTime: (time: number) => void;
  }
  
  
  interface ICocktailRecipe {
    idDrink: string;
    strDrink: string;
    strDrinkAlternate: string | null;
    strTags: string | null;
    strVideo: string | null;
    strCategory: string;
    strIBA: string | null;
    strAlcoholic: string;
    strGlass: string;
    strInstructions: string;
    strInstructionsES: string | null;
    strInstructionsDE: string | null;
    strInstructionsFR: string | null;
    strInstructionsIT: string | null;
    strInstructionsZH_HANS: string | null;
    strInstructionsZH_HANT: string | null;
    strDrinkThumb: string;
    strIngredient1: string | null;
    strIngredient2: string | null;
    strIngredient3: string | null;
    strIngredient4: string | null;
    strIngredient5: string | null;
    strIngredient6: string | null;
    strIngredient7: string | null;
    strIngredient8: string | null;
    strIngredient9: string | null;
    strIngredient10: string | null;
    strIngredient11: string | null;
    strIngredient12: string | null;
    strIngredient13: string | null;
    strIngredient14: string | null;
    strIngredient15: string | null;
    strMeasure1: string | null;
    strMeasure2: string | null;
    strMeasure3: string | null;
    strMeasure4: string | null;
    strMeasure5: string | null;
    strMeasure6: string | null;
    strMeasure7: string | null;
    strMeasure8: string | null;
    strMeasure9: string | null;
    strMeasure10: string | null;
    strMeasure11: string | null;
    strMeasure12: string | null;
    strMeasure13: string | null;
    strMeasure14: string | null;
    strMeasure15: string | null;
    strImageSource: string | null;
    strImageAttribution: string | null;
    strCreativeCommonsConfirmed: string | null;
    dateModified: string | null;
  }
  
  interface IApiCocktailData {
    drinks: ICocktailRecipe[];
  }